try:
    print(x)
except:
    print("exception or error")